# Generated by Django 4.2 on 2023-05-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201126_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
